[gcp_service_account]
type = "service_account"
project_id = "sharqawi-reports"
private_key_id = "0e89fb6c3b249051468f145ca25a5a81a75778a4"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDZKBtNzjphiHSq
eef16775ufL9DVEpx5pb3G6ZHVDYGwTY+NWjIwMol54MyUWym39D2silpaoK/RB8
XUUQd64m/IdSWFyhEuBsUH70b3ZYobLP4FqyFGWO2Jg1eut+5LvLPzpnW2L2vlqk
195z+/JSEP0rZrsJpnr5y3KyFpSwWVxnfWt4x2W8DILxhJqz1Um50wE52q/ZJ2+F
SwvPMz7HOMNJwb8ixYt6NbHNltI4ghGQpVBx0mzZtLButRRX7l6s8zhoq4hqkQpX
9SmKkLv+9vk+nQKjt1IUpkc94BL2Ul6UJtc9pwFtq1EKyITori70TDTRpxlpU+hx
5WlUmp1dAgMBAAECggEAAyrumwfzGhEfgo0csR2rP4FS5hYXpQBgZA6nHlyrHTvn
qjKXCzYriaAMkistdRmHlbnPS3tLK7XdU7MYmtDkHXV5k93uG/tmgq357B7kHw7c
yOOA7zAU+yx1q/ILFWLIyoI1m+RdYTQNpnHvsMlwE3pj9wocmFtxV8t79NUXfisI
qQjgYK1X6MsfoRwzR9EQS9k3RDMXM9D1TG90WJ0fwoDWjh7U26XKNHYSfQO9n0/k
qWkZfeBf/jZDE+TMs+0bGDkW1HdBfKpdKETVbsXMxuoKZlQ8hpDDzbVcoIFqZDzQ
ZlAqYPfkwaVYZ3jH/sEUvqPbZeln2TBwkYO2ASdAgQKBgQDs/3o9vASfw+sbU1JL
SHUqj54aKmpL3EooCjecHQzP7tzxa7R+sdos8lE2iMhOO3TwdShN07P/9Fr2KpEh
+bpWs0tTHx4t32CO23CNBfNwmVfuvoTkWrISdRUyjHDiaWisUD4FnrlebQ87oDDN
6iFMr7+2dLirLxWXA1x/XpL1BQKBgQDqkV/9HtgJ8win0ro9NKfbcH8MK7p1ayXR
SIf67KsnLeOR4OTShaIJTwxlBQNdrnP2+/QzF7pPSFyYe988FOHQ/eQh7OBg/dcX
KpQ5AiRgoNmZ7skpUT50hHn2M5CwpLDBfquUQ0YUIUB9GN6NWDyu7aBMng4X159R
+scrEYr2eQKBgQCQpl210EwCN1IIG5Le4BqjH4Uf80Ntica5KYNHhXOMdf3kXBiO
O38ub7eh0VpwZVm6acdvuQbj8gCSvuhWFFXnFQekdBm3Zd9JUiYf7MHot68zyJTT
y4dkPJHziERd7Hg2s8MnKvl46JejjOI8y+oHJD2e3x7XXKWQxjxugQqxAQKBgAEa
Nc1Gu9UwIzZGs0FeYfuSB8bS3cl3e3IEWT9ApX1FpfAlkm262wwYJwLCh0WFcF4U
yQ0Ea4e721OMIXxyzKzixJO0PUm3Z69gL9okvG8H0n36tU9QZm69wKT7kQ6Dd6Ex
KzVDK60kit0LpOAdLgvUahByHbbW+JS2DQGSz4hhAoGARGSMnHX5eua0MtCsMeEf
Wrl4463xUQoaNK26uBpVhI8dZE3YbaRuXIWAFBmvZPuknatIZdhw/DtkWcXOkKtN
qRFdu8RqFtbCInvV1k5ibdU426/jd3dUHG5R4EkuTsgQpLZXtNriemf9Vaig+muw
N6MXaS2z0QIfOvvoW+tMPNg=
-----END PRIVATE KEY-----"""
client_email = "streamlit-gsheets-access@sharqawi-reports.iam.gserviceaccount.com"
client_id = "105710636372862578067"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-gsheets-access%40sharqawi-reports.iam.gserviceaccount.com"
